### ISSUE TITLE
Request: adding `py.typed` to export typing for `mypy`

### ISSUE THREAD

**Issue by jamesbraza** [openreview/openreview-py#2551]
Users checking their code with static type checkers such as `mypy` get this error:

```none
error: Cannot find implementation or library stub for module named "openreview"  [import-not-found]
        import openreview
    ^
```

Can you add a `py.typed` so `openreview` will have associated type hints.

This is with Python 3.12.8 and `mypy==1.15.0`.

In the meantime, to work around it:

```toml
[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["openreview"]
```
